# This file was generated by GoReleaser. DO NOT EDIT.
cask "gelete" do
  name "gelete"
  desc "Interactive git branch deletion tool with TUI"
  homepage "https://github.com/Kdaito/gelete"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gelete"

  on_macos do
    on_intel do
      url "https://github.com/Kdaito/gelete/releases/download/v#{version}/gelete_#{version}_Darwin_x86_64.tar.gz"
      sha256 "816318fff2a9d430d700bbe0e33ad9636739f4aaf9df65ce85ddf8161bf07243"
    end
    on_arm do
      url "https://github.com/Kdaito/gelete/releases/download/v#{version}/gelete_#{version}_Darwin_arm64.tar.gz"
      sha256 "47ddb6077c09727e64e76d9f82ba05f45d6b0ebcfa02be2fe8c3db9af71efdf8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Kdaito/gelete/releases/download/v#{version}/gelete_#{version}_Linux_x86_64.tar.gz"
      sha256 "fec259aff63d5a94c85c766b2d7a704c86bdac461380ddbdf15a7194581a05d0"
    end
    on_arm do
      url "https://github.com/Kdaito/gelete/releases/download/v#{version}/gelete_#{version}_Linux_arm64.tar.gz"
      sha256 "9c8ce2119edb01caad1ff4cdd4d7d3039666d44084b0972654e46bfde50c89ae"
    end
  end

  # No zap stanza required
end
