# This file was generated by GoReleaser. DO NOT EDIT.
cask "gelete" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "cb9e073433589de2358ba5e5280a76a8f83b2ec34507996c8975231bd21b47b2"
      url "https://github.com/Kdaito/gelete/releases/download/v#{version}/gelete_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "87857f158e690297bb7690a8e707a50708d1f43c52f26416935547d6eb361be2"
      url "https://github.com/Kdaito/gelete/releases/download/v#{version}/gelete_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cd69721457787d77fc9adb346e8865676922cf8f44bb412f9009647fc98c2548"
      url "https://github.com/Kdaito/gelete/releases/download/v#{version}/gelete_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0236bbbe4d989e46163fd5fb4cb8238513438d68a3b9918ae33d4e7f0e676f0c"
      url "https://github.com/Kdaito/gelete/releases/download/v#{version}/gelete_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "gelete"
  desc "Interactive git branch deletion tool with TUI"
  homepage "https://github.com/Kdaito/gelete"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gelete"

  # No zap stanza required

end
