# This file was generated by GoReleaser. DO NOT EDIT.
cask "gelete" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "649c76ca42e114819b7a632cf52da2c6c41562f581a0c6369497127fbaf657de"
      url "https://github.com/Kdaito/gelete/releases/download/v#{version}/gelete_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9778395b7b873945bd25ef60ff7b196861c4a763b5141ee6399e42c337b8a06a"
      url "https://github.com/Kdaito/gelete/releases/download/v#{version}/gelete_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c728d3d981fc54968b1891a234bab4f574cf92b5dd7145de245b09370f0569ac"
      url "https://github.com/Kdaito/gelete/releases/download/v#{version}/gelete_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1f9850d99ef2c6594b1bad39222ba4e3df53b0f86cc8a750e8b45280e5cd4458"
      url "https://github.com/Kdaito/gelete/releases/download/v#{version}/gelete_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "gelete"
  desc "Interactive git branch deletion tool with TUI"
  homepage "https://github.com/Kdaito/gelete"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gelete"

  # No zap stanza required

end
